# Generated by Django 3.2.3 on 2021-10-10 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='people',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Audio_store',
            },
        ),
        migrations.CreateModel(
            name='BinaryRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person1_in_room', to=settings.AUTH_USER_MODEL)),
                ('person2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person2_in_room', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='binary_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.binaryroom'),
        ),
    ]
