# Generated by Django 3.2.3 on 2021-10-10 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20211010_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='people',
        ),
        migrations.AddField(
            model_name='room',
            name='people',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
